### PR TITLE
Case study emc (geothermal)

### PR DESCRIPTION
**Pull request by sdevriese**
A new case study on the Elevenmile Canyon geothermal region using ZTEM. 
Still needs a few things regarding the method/data
- [ ] what is ztem? Link to Maxwell 3 FDEM page on ZTEM (needs to be created) or include here?
- [ ] An example of ZTEM using block in halfspace has been included on the emc_data page. Is this the best location of should it go to Maxwell 3 ZTEM page, which doesn't exist?
- [ ] need to work on properties page... to come!

Suggested reviewers:

- [ ] @dougoldenburg 
- [ ] @grosenkj 

Before merging: please run a spell check through your documents!

### CODE REVIEW

**Comment by sdevriese** [comment]
Hey @grosenkj, do you have any comments on this case study you want to include or want me to address? Hoping to get this to Doug soon =)

**Comment by sdevriese** [comment]
@lheagy The error comes from referencing the aspen case study but it's on another branch. So Aspen (when reviewed) should be added to master, then master merged here, and everything should work fine. =)

**Comment by lheagy** [comment]
em 2016-07-03 13-14-08
will resolve a number of testing issues

**Comment by sdevriese** [comment]
@lheagy all checks passed for elevenmile canyon case history =) ready to merge unless you want to do some other changes.

**Pull request merged**
