### PR TITLE
Wave equation

### PR DESCRIPTION
**Pull request by sdevriese**
Short summary of changes / additions
Derivation of wave equation from Maxwell's

Suggested reviewers:
- Doug Oldenburg @dougoldenburg

### CODE REVIEW

**Comment by lheagy** [comment]
@fourndo @micmitch : can you guys take a look??

**Comment by lheagy** [comment]
The fail looks like it is out-of-date. I would suggest merging master in first and then going from there

**Comment by lheagy** [comment]
@sdevriese : is this branch good to go? or did you want to do some more things on it? Feel free to merge the pull request if you are happy with it!
wave equation by sdevriese pull request 93 ubcgif em 2016-05-04 21-54-58

**Comment by sdevriese** [comment]
@lheagy Not yet, I think. @fourndo and @micmitch were going to read through it and provide feedback. And I think @dougoldenburg wants to go through it too.

**Comment by micmitch** [comment]
@sdevriese Sent you an email last night with my thoughts about the section. Hope that they are helpful!

**Pull request closed without merging**
