### PR TITLE
Fixed spelling and "Moondarra Shales"

### PR DESCRIPTION
**Pull request by krisdavis**
Exactly what the title says.

### CODE REVIEW

**Comment by fourndo** [comment]
Hey Kris, can check something in Processing.
There is a link needed to somewhere, but not sure to where

**Comment by krisdavis** [comment]
Dom,

It's actually here: /maxwell1_fundamentals/formative_laws/lenz.rst
I literally simply change the spelling of "chargeabilty" I'll see if I can do something about this.

**Comment by krisdavis** [comment]
@lheagy Help!?

**Comment by lheagy** [comment]
Looks like the link that errored is ok, so I restarted the test. 
em - travis ci 2016-07-11 11-12-12

**Comment by krisdavis** [comment]
Oh ok. I didn't realize I was not signed into Travis. If you are not signed in, you cannot see the refresh button. Important detail.

**Pull request merged**
