### PR TITLE
add radio button widget for airborne fdem

### PR DESCRIPTION
**Pull request by lheagy**
Images and radio buttons for airborne fdem basic physics. 

@fourndo, @yangdikun : see what you think
 
image

### CODE REVIEW

**Comment by lheagy** [comment]
- [ ] prior to merging, the text for the widget should be updated (@lheagy) 

image

**Comment by fourndo** [comment]
@lheagy I forgot about your branch and created another one: GeopSurvey_AFEM. 
Want to merge this in here?

**Comment by lheagy** [comment]
up to you! This is small, so we could easily merge it onto the branch you are working on

**Comment by fourndo** [comment]
Merged in, will continue the work on Geop survey afem #396

**Pull request merged**
